### ISSUE TITLE
Add Consumables Tracking

### ISSUE THREAD

**Issue by brhahlen** [hay-kot/homebox#544]
### What is the problem you are trying to solve with this feature?

HomeBox is great for knowing what is where in your house, but it is focused on "static" items, such as TV's, monitor's, etc.
As I was putting in my different locations, I got to the point where I started entering a drawer in a closet, where I keep the replaceable parts for my robot vacuum (filter, brush, etc).
I can easily add this, but, I can not easily remove one from the stock when I replace the filter on the vacuum, for instance.

In another location, I keep a bunch of batteries for my sensors, which need replacing every once in a while. It'd be great if I could then go into HomeBox and "remove" one battery from the total amount.

### What is the solution you are proposing?

Add a new `Consumable` type, that foregoes the `Insured` field (for one, probably others), and adds a `+` and `-` field next to the Quantity field, to easily add one or more.

### What alternatives have you considered?

Currently editing manually, but it is cumbersome.

### Additional context

In the future, there would then also be an option to "link" a consumable to an item/asset.

For instance, I would look at my Vacuum, and see that it has one filter in use, but there are 2 filters still in the drawer, so I don't need to buy a new one right now.
If that makes sense.

### Contributions

- [X] I have searched through existing issues and feature requests to see if my idea has already been proposed.
- [ ] If this feature is accepted, I would be willing to help implement and maintain this feature.
- [ ] If this feature is accepted, I'm willing to sponsor the development of this feature.

**Comment by hay-kot** [comment]
Hey! This isn't really the focus of this project. I'd suggest using another project that is more focused on consumables. Thanks!

**Comment by brhahlen** [comment]
Thanks for the update @hay-kot !
I've since installed Grocy alongside HomeBox, and will use these two in conjunction :)

Thanks again for all your hard work!
